### ISSUE TITLE
Does it necessary to have an assembled genome to run PiRATE

### ISSUE THREAD

**Issue by majie5976** [JBerthelier/PiRATE#36] opened 2020-06-19 08:48 UTC
Hi @JBerthelier , 
Hope all is fine with you. Before running PiRATE pipeline I just want to confirm that, Does it necessary to have an assembled genome to run PiRATE pipeline. Because species I'm working on not possible to have an assembled genome due to large genome size. Can I use approach 4 (build repeated elements) in step one, then proceed the following steps as it is. The questions why I'm asking because I checked the final step TEannot there is two input requirements 
1. genomic Sequences (**Enter the genome assembly**) 
2. TE Library (the manually constructed TE Libraries) If I'm not worng. 
Your suggestions would be appreciated !
Thanks
Regards,
Majie

**Comment by JBerthelier** [comment] 2020-06-22 06:37
this is a duplicate of #37  , thus I close it

**Closed** 2020-06-22 06:39 UTC
